baseurl = "https://example.com/"
languageCode = "en-us"
title = "Parag Kar"
staticDir = ["static"]

# Pagination
paginate = 10
paginatePath = "page"

# Theme to use
theme = "hugo-material-blog"

# Copyright, appears in the footer
copyright = "© 2018 Parag Kar"

# Links format
[permalinks]
  post = "/:year/:month/:title/"

# Localization
defaultContentLanguage = "en"

# English
[languages.en]
  languageName = "English"


# Other params
[params]
  # Display post summaries instead of content in list templates (default: true)
  # truncate = false