baseurl = "https://paragkar.github.io/"
languageCode = "en-us"
title = "Parag Kar"
staticDir = ["static"]

# Pagination
paginate = 2
paginatePath = "page"

# Theme to use
theme = "hugo-material-blog"

# Copyright, appears in the footer
copyright = "© 2018 Parag Kar"

# Links format
[permalinks]
  post = "/:title/"

# Localization
defaultContentLanguage = "en"

# English
[languages.en]
  languageName = "English"

# Other params
[params]
  # Display post summaries instead of content in list templates (default: true)
  # truncate = false
  facebookLink = "https://www.facebook.com/parag.kar.7"
  linkedinLink = "https://www.linkedin.com/in/paragkar/"
  twitterLink = "https://twitter.com/parag_kar?lang=en"
  instagramLink = "https://www.instagram.com/parag_kar/"